[package]
org = "ballerinax"
name = "googleapis.drive"
version = "0.1.6"
export= ["googleapis.drive", "googleapis.drive.listener"]
authors = ["Ballerina"]
keywords = ["google", "drive", "storage"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.drive"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-0.1.6.jar"
groupId = "org.ballerinalang.googleapis.drive"
artifactId = "java-wrapper"
version = "0.1.6"
