[package]
distribution = "2201.0.3"
org = "ballerinax"
name = "googleapis.drive"
version = "3.0.0"
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.drive"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
